import { NutrientDefinition } from './types';

export const DEFAULT_NUTRIENTS: NutrientDefinition[] = [
  // 蛋白質與胺基酸類
  { id: 'crude_protein', name: '粗蛋白質', nameEn: 'Crude Protein', category: 'protein_amino', unit: 'g', order: 1 },
  { id: 'arginine', name: '精胺酸', nameEn: 'Arginine', category: 'protein_amino', unit: 'g', order: 2 },
  { id: 'histidine', name: '組胺酸', nameEn: 'Histidine', category: 'protein_amino', unit: 'g', order: 3 },
  { id: 'isoleucine', name: '異亮胺酸', nameEn: 'Isoleucine', category: 'protein_amino', unit: 'g', order: 4 },
  { id: 'leucine', name: '亮胺酸', nameEn: 'Leucine', category: 'protein_amino', unit: 'g', order: 5 },
  { id: 'lysine', name: '離胺酸', nameEn: 'Lysine', category: 'protein_amino', unit: 'g', order: 6 },
  { id: 'methionine', name: '甲硫胺酸', nameEn: 'Methionine', category: 'protein_amino', unit: 'g', order: 7 },
  { id: 'methionine_cystine', name: '甲硫胺酸-胱胺酸', nameEn: 'Methionine-cystine', category: 'protein_amino', unit: 'g', order: 8 },
  { id: 'phenylalanine', name: '苯丙胺酸', nameEn: 'Phenylalanine', category: 'protein_amino', unit: 'g', order: 9 },
  { id: 'phenylalanine_tyrosine', name: '苯丙胺酸-酪胺酸', nameEn: 'Phenylalanine-tyrosine', category: 'protein_amino', unit: 'g', order: 10 },
  { id: 'threonine', name: '蘇胺酸', nameEn: 'Threonine', category: 'protein_amino', unit: 'g', order: 11 },
  { id: 'tryptophan', name: '色胺酸', nameEn: 'Tryptophan', category: 'protein_amino', unit: 'g', order: 12 },
  { id: 'valine', name: '纈胺酸', nameEn: 'Valine', category: 'protein_amino', unit: 'g', order: 13 },
  // 脂肪與脂肪酸類
  { id: 'crude_fat', name: '粗脂肪', nameEn: 'Crude Fat', category: 'fat_fatty', unit: 'g', order: 14 },
  { id: 'linoleic_acid', name: '亞麻油酸', nameEn: 'Linoleic acid', category: 'fat_fatty', unit: 'g', order: 15 },
  { id: 'alpha_linolenic_acid', name: 'α-次亞麻油酸', nameEn: 'alpha-Linolenic acid', category: 'fat_fatty', unit: 'g', order: 16 },
  { id: 'arachidonic_acid', name: '花生四烯酸', nameEn: 'Arachidonic acid', category: 'fat_fatty', unit: 'g', order: 17 },
  { id: 'epa_dha', name: 'EPA + DHA', nameEn: 'EPA + DHA', category: 'fat_fatty', unit: 'g', order: 18 },
  // 礦物質類
  { id: 'calcium', name: '鈣', nameEn: 'Calcium', category: 'mineral', unit: 'g', order: 19 },
  { id: 'phosphorus', name: '磷', nameEn: 'Phosphorus', category: 'mineral', unit: 'g', order: 20 },
  { id: 'potassium', name: '鉀', nameEn: 'Potassium', category: 'mineral', unit: 'g', order: 21 },
  { id: 'sodium', name: '鈉', nameEn: 'Sodium', category: 'mineral', unit: 'mg', order: 22 },
  { id: 'chloride', name: '氯', nameEn: 'Chloride', category: 'mineral', unit: 'g', order: 23 },
  { id: 'magnesium', name: '鎂', nameEn: 'Magnesium', category: 'mineral', unit: 'g', order: 24 },
  { id: 'iron', name: '鐵', nameEn: 'Iron', category: 'mineral', unit: 'mg', order: 25 },
  { id: 'copper_extruded', name: '銅 (擠壓成型)', nameEn: 'Copper - Extruded', category: 'mineral', unit: 'mg', order: 26 },
  { id: 'copper_canned', name: '銅 (罐頭)', nameEn: 'Copper - Canned', category: 'mineral', unit: 'mg', order: 27 },
  { id: 'manganese', name: '錳', nameEn: 'Manganese', category: 'mineral', unit: 'mg', order: 28 },
  { id: 'zinc', name: '鋅', nameEn: 'Zinc', category: 'mineral', unit: 'mg', order: 29 },
  { id: 'iodine', name: '碘', nameEn: 'Iodine', category: 'mineral', unit: 'mg', order: 30 },
  { id: 'selenium', name: '硒', nameEn: 'Selenium', category: 'mineral', unit: 'mg', order: 31 },
  // 維生素與其他類
  { id: 'vitamin_a', name: '維生素 A', nameEn: 'Vitamin A', category: 'vitamin_other', unit: 'IU', order: 32 },
  { id: 'vitamin_d', name: '維生素 D', nameEn: 'Vitamin D', category: 'vitamin_other', unit: 'IU', order: 33 },
  { id: 'vitamin_e', name: '維生素 E', nameEn: 'Vitamin E', category: 'vitamin_other', unit: 'IU', order: 34 },
  { id: 'vitamin_k', name: '維生素 K', nameEn: 'Vitamin K', category: 'vitamin_other', unit: 'mg', order: 35 },
  { id: 'thiamine', name: '硫胺素', nameEn: 'Thiamine', category: 'vitamin_other', unit: 'mg', order: 36 },
  { id: 'riboflavin', name: '核黃素', nameEn: 'Riboflavin', category: 'vitamin_other', unit: 'mg', order: 37 },
  { id: 'pantothenic_acid', name: '泛酸', nameEn: 'Pantothenic acid', category: 'vitamin_other', unit: 'mg', order: 38 },
  { id: 'niacin', name: '菸鹼酸', nameEn: 'Niacin', category: 'vitamin_other', unit: 'mg', order: 39 },
  { id: 'pyridoxine', name: '吡哆醇', nameEn: 'Pyridoxine', category: 'vitamin_other', unit: 'mg', order: 40 },
  { id: 'folic_acid', name: '葉酸', nameEn: 'Folic acid', category: 'vitamin_other', unit: 'mg', order: 41 },
  { id: 'biotin', name: '生物素', nameEn: 'Biotin', category: 'vitamin_other', unit: 'mg', order: 42 },
  { id: 'vitamin_b12', name: '維生素 B₁₂', nameEn: 'Vitamin B₁₂', category: 'vitamin_other', unit: 'mg', order: 43 },
  { id: 'choline', name: '膽鹼', nameEn: 'Choline', category: 'vitamin_other', unit: 'mg', order: 44 },
  { id: 'taurine_extruded', name: '牛磺酸 (擠壓成型)', nameEn: 'Taurine - Extruded', category: 'vitamin_other', unit: 'g', order: 45 },
  { id: 'taurine_canned', name: '牛磺酸 (罐頭)', nameEn: 'Taurine - Canned', category: 'vitamin_other', unit: 'g', order: 46 },
  // 碳水化合物類
  { id: 'carbohydrate', name: '碳水化合物', nameEn: 'Carbohydrate', category: 'carbohydrate', unit: 'g', order: 47 },
];
